# <center>Decolagem da Missão: Ignition Zero - O Início da Aurora<center>

Aluna: Natália Souza Carvalho
RM: 569068 - Turma: 1CCOA - Semestre: 2026/1

## 5.1 Organização e descrição da telemetria

Protocolo de Telemetria: Critérios de Decolagem (DECOLAR / ABORTAR)

Este protocolo define os limites operacionais estritos para a autorização de lançamento da nave **Aurora Siger**. Qualquer valor fora das faixas especificadas abaixo resulta em **Abortar decolagem**.

| Variável | Descrição | Parâmetro Nominal (DECOLAR) | Ação em Caso de Falha (ABORTAR) |
| :--- | :--- | :--- | :--- |
| `temp_interna` | Temperatura do módulo de comando. | **18°C a 26°C** | ABORTAR: Risco à integridade do hardware/tripulação. |
| `temp_externa` | Temperatura da fuselagem externa. | **-100°C a 150°C** | ABORTAR: Condições ambientais fora do limite de proteção. |
| `integridade` | Sensores de integridade estrutural. | **1 (True)** | ABORTAR: Falha estrutural ou fissura detectada. |
| `energia` | Nível de carga das baterias principais. | **> 80%** | ABORTAR: Autonomia insuficiente para a subida. |
| `pressao_psi` | Pressão interna dos tanques (PSI). | **450 a 550 PSI (Pound-Force per Square Inch ou Libra-Força por Polegada Quadrada)** | ABORTAR: Risco de explosão ou falha de ignição. |
| `status` | Diagnóstico de módulos críticos. | **1 (True)** | ABORTAR: Falha em subsistema vital ou perda de sinal. |

A organização da telemetria foi estruturada com o objetivo de representar, os principais parâmetros para a validação da decolagem da nave.

A variável temp_interna representa a temperatura do módulo de comando, sendo um indicador das condições internas da nave. Foi definido um intervalo entre 18°C e 26°C, garantindo segurança tanto para os sistemas eletrônicos quanto para a tripulação. Valores fora dessa faixa indicam risco de superaquecimento ou falha operacional, resultando na interrupção da missão.

Já a temp_externa reflete as condições ambientais enfrentadas pela fuselagem. Como o ambiente externo é mais extremo, foi estabelecida uma faixa mais ampla, entre -100°C e 150°C. Valores fora desse intervalo podem comprometer a estrutura da nave ou a eficiência dos sensores.

A variável integridade é um indicador binário que representa a condição estrutural da nave. O valor 1 indica que não há falhas detectadas, enquanto o valor 0 representa problemas estruturais. Por se tratar de um fator crítico, qualquer inconsistência resulta automaticamente na interrupção da missão.

O nível de energia corresponde à carga disponível nas baterias principais. Foi definido um valor mínimo superior a 80%, assegurando autonomia suficiente para suportar as demandas energéticas da decolagem. Níveis abaixo desse limite indicam risco operacional.

A variável pressao refere-se à pressão interna dos tanques de combustível, sendo um parâmetro fundamental para o funcionamento adequado dos motores. A faixa segura foi definida entre 450 e 550 PSI, pois valores fora desse intervalo podem causar falhas de ignição ou até riscos de explosão.

Por fim, o status dos módulos críticos também é representado de forma binária, indicando se os subsistemas essenciais estão operacionais. Um valor verdadeiro (1) garante o funcionamento adequado, enquanto qualquer falha implica na impossibilidade de prosseguir com a decolagem.

## 5.2 Algoritmo de Verificação

### Pseudocódigo

FUNÇÃO analisar_componentes(df):

    Criar coluna "Obs" vazia
    Criar coluna "decolagem" com valor padrão "DECOLAR"

    PARA cada linha i do dataframe:

        Criar lista obs vazia
        Definir abortar = FALSO

        SE temp_interna < 18 OU temp_interna > 26:
            abortar = VERDADEIRO
            adicionar "Risco à integridade do hardware/tripulação" em obs

        SE temp_externa < -100 OU temp_externa > 150:
            abortar = VERDADEIRO
            adicionar "Condições ambientais fora do limite de proteção" em obs

        SE integridade ≠ 1:
            abortar = VERDADEIRO
            adicionar "Falha estrutural ou fissura detectada" em obs

        SE energia ≤ 0.80:
            abortar = VERDADEIRO
            adicionar "Autonomia insuficiente para a subida" em obs

        SE pressao_psi < 450 OU pressao > 550:
            abortar = VERDADEIRO
            adicionar "Risco de explosão ou falha de ignição" em obs

        SE status ≠ 1:
            abortar = VERDADEIRO
            adicionar "Falha em subsistema vital ou perda de sinal" em obs

        SE abortar = VERDADEIRO:
            definir decolagem = "ABORTAR"
            definir Obs = juntar mensagens de obs
        SENÃO:
            definir Obs = "OK"

    RETORNAR df atualizado

## 5.3 Script em Python

In [8]:
import pandas as pd

In [9]:
# Função para análise de componentes da nave e seus status final (ABORTAR/DECOLAR)
# Essa função vai levar como base o protócolo decidido para o lançamento ou não da nave Aurora. Fazendo todas as verificações necessárias 
# o método cria duas colunas "Obs" e "decolagem". A coluna "obs" anotará todas as falhas notadas e o campo de decolagem trará o status final.
def analisar_componentes(df: pd.DataFrame):
    df['Obs'] = ""
    df['decolagem'] = "DECOLAR"

    for i in range(len(df)):
        obs = []
        abortar = False
        # Temp_interna deve ser >= 18°C e <= 26°C:
        if df.loc[i, "temp_interna"] < 18 or df.loc[i, "temp_interna"] > 26:
            abortar = True
            obs.append("Risco à integridade do hardware/tripulação")
        # Temp_externa deve ser >= -100°C e <= 150°C
        if df.loc[i, 'temp_externa'] < -100 or df.loc[i, 'temp_externa'] > 150:
            abortar = True
            obs.append("Condições ambientais fora do limite de proteção")
        # Integridade deve ser = 1
        if df.loc[i, "integridade"] != 1:
            abortar = True
            obs.append("Falha estrutural ou fissura detectada")
        # Energia deve ser > 0.80 (80%)
        if df.loc[i, 'energia'] <= 0.80:
            abortar = True
            obs.append("Autonomia insuficiente para a subida")
        # Pressão deve ser >= 450 e <= 550
        if df.loc[i, 'pressao_psi'] < 450 or df.loc[i, 'pressao_psi'] > 550:
            abortar = True
            obs.append("Risco de explosão ou falha de ignição")
        # Status deve ser = 1
        if df.loc[i, 'status'] != 1:
            abortar = True
            obs.append("Falha em subsistema vital ou perda de sinal")

        if abortar:
            df.loc[i, 'decolagem'] = "ABORTAR"
            df.loc[i, 'Obs'] = ", ".join(obs)
        else:
            df.loc[i, 'Obs'] = "OK"

    return df


# Leitura da base de dados
df_nave = pd.read_csv('dados_nave.csv',sep=',')
# Atualizando a base
df_nave_analizado = analisar_componentes(df_nave)
display(df_nave_analizado)

,temp_interna,temp_externa,energia,pressao_psi,integridade,status,Obs,decolagem
0,16,140,0.18,400,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR
1,29,110,0.02,364,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR
2,38,-80,0.49,467,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR
3,24,-93,0.18,342,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR
4,20,14,0.37,343,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR
...,...,...,...,...,...,...,...,...
145,26,32,0.80,340,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR
146,17,73,0.68,527,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR
147,12,42,0.57,491,1,False,"Risco à integridade do hardware/tripulação, Au...",ABORTAR
148,12,87,0.13,444,0,True,"Risco à integridade do hardware/tripulação, Fa...",ABORTAR
149,10,48,0.81,500,1,True,Risco à integridade do hardware/tripulação,ABORTAR

## 5.4 Análise Energética

Capacidade Total = 190 kwh;
Consumo estimado = 20 kwh;
Perdas energéticas = 10% 

ENERGIA > 120 = "SUFICIENTE";
ENERGIA > 60 AND ENERGIA < 120 = "ALERTA";
ENERGIA < 60 = "INSUFICIENTE"

A análise energética foi estruturada com o objetivo de avaliar se a nave possui autonomia suficiente para realizar a decolagem com segurança, considerando o consumo operacional e as perdas.

Inicialmente, foi definida a capacidade total da nave em 190 kWh, representando o limite máximo de armazenamento energético disponível. A partir disso, considerou-se um consumo estimado de 20 kWh durante o processo de decolagem.

Além disso, foi incorporado ao modelo uma perda energética de 10%, refletindo ineficiências naturais do sistema, como dissipação térmica, conversões de energia, etc.

Com base nesses parâmetros, foram definidos três níveis de classificação energética. Valores de energia superiores a 120 kWh foram considerados “suficientes”, garantindo uma margem de segurança adequada mesmo após o consumo e as perdas previstas. Já valores abaixo de 120 kWh foram classificados como “alerta”, indicando que, embora a nave ainda possa operar, há redução na margem de segurança energética. Por fim, níveis inferiores a 60 kWh foram considerados “insuficientes”, representando um cenário crítico em que a energia disponível não é capaz de sustentar a operação de forma segura.

Apesar dessa análise mais detalhada sobre a energia das baterias, foi definido anteriormente que apenas níveis acima de 80% poderiam resultar na decolagem da nave, sendo assim, baterias em níveis de "ALERTA" e "INSUFICIENTE" não vão decolar.

In [10]:
capacidade_total = 190
perda_energetica = 0.1
consumo_estimado = 20

for i in range(0,len(df_nave_analizado)):
    # Calcular energia disponível
    energia_disp = capacidade_total * df_nave_analizado.loc[i,"energia"]
    
    # Perdas energéticas
    energia_disp = energia_disp * (1 - perda_energetica)
    
    # Consumo da embalagem
    energia_disp = energia_disp - consumo_estimado
    
    df_nave_analizado.loc[i,"energia_restante_kwh"]= round(energia_disp,2)
    
    # Status da energia restante
    # Maior que 120 = SUFICIENTE
    if df_nave_analizado.loc[i,'energia_restante_kwh'] > 120:
        df_nave_analizado.loc[i,'status_energia'] = 'SUFICIENTE'
    # Maior que 60 = ALERTA
    elif df_nave_analizado.loc[i,'energia_restante_kwh'] > 60:
        df_nave_analizado.loc[i,'status_energia']='ALERTA'
    # Menor que 60 = INSUFICIENTE
    else:
        df_nave_analizado.loc[i,'status_energia']='INSUFICIENTE'
        
    
display(df_nave_analizado)

,temp_interna,temp_externa,energia,pressao_psi,integridade,status,Obs,decolagem,energia_restante_kwh,status_energia
0,16,140,0.18,400,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR,10.78,INSUFICIENTE
1,29,110,0.02,364,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR,-16.58,INSUFICIENTE
2,38,-80,0.49,467,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR,63.79,ALERTA
3,24,-93,0.18,342,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR,10.78,INSUFICIENTE
4,20,14,0.37,343,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR,43.27,INSUFICIENTE
...,...,...,...,...,...,...,...,...,...,...
145,26,32,0.80,340,1,True,"Autonomia insuficiente para a subida, Risco de...",ABORTAR,116.80,ALERTA
146,17,73,0.68,527,1,True,"Risco à integridade do hardware/tripulação, Au...",ABORTAR,96.28,ALERTA
147,12,42,0.57,491,1,False,"Risco à integridade do hardware/tripulação, Au...",ABORTAR,77.47,ALERTA
148,12,87,0.13,444,0,True,"Risco à integridade do hardware/tripulação, Fa...",ABORTAR,2.23,INSUFICIENTE
149,10,48,0.81,500,1,True,Risco à integridade do hardware/tripulação,ABORTAR,118.51,ALERTA

## 5.5 Análise Assistida por IA

### Classificação dos Dados
A base de dados foi composta por 150 registros simulando diferentes cenários operacionais da nave antes da decolagem. As variáveis analisadas incluem parâmetros térmicos, estruturais, energéticos e operacionais, permitindo uma visão integrada das condições da missão.

A classificação dos dados energéticos, representada pela variável status_energia, demonstrou predominância de cenários classificados como “INSUFICIENTE”, totalizando a maior parte dos registros. Em seguida, foram observados casos classificados como “ALERTA” e, em menor quantidade, situações consideradas “SUFICIENTE”.

Essa distribuição indica que grande parte dos cenários simulados apresenta limitações energéticas, o que reforça a importância da análise prévia antes da tomada de decisão. Além disso, a presença de diferentes classificações demonstra que a base contempla tanto cenários críticos quanto operacionais, tornando-a adequada para testes de validação do algoritmo de decolagem.

### Identificação de anomalias
A análise exploratória dos dados permitiu identificar algumas anomalias relevantes. Foram observados valores negativos na variável energia_restante_kwh, indicando cenários em que o consumo energético ultrapassa a capacidade disponível, o que caracteriza uma condição crítica e inviável para a operação.

Além disso, verificou-se a presença de valores de temp_interna fora da faixa ideal definida (18°C a 26°C), sugerindo possíveis riscos de superaquecimento ou operação fora das condições seguras para os sistemas internos.

Por fim, a dispersão dos dados energéticos, evidenciada pelo desvio padrão elevado da energia restante, indica variações significativas entre os cenários, o que pode impactar diretamente a previsibilidade e a estabilidade da missão.

### Sugestão de risco
Com base na análise realizada, foram identificados três principais níveis de risco operacional. O primeiro está relacionado ao risco energético, evidenciado pela alta incidência de cenários com energia insuficiente ou negativa. Esse fator pode comprometer diretamente a continuidade da missão e deve ser tratado como critério crítico de decisão.

O segundo refere-se ao risco térmico, associado a desvios nas temperaturas internas e externas. Condições fora dos limites ideais podem impactar tanto a integridade dos sistemas quanto a segurança da operação, exigindo monitoramento rigoroso.

O terceiro está ligado ao risco estrutural e operacional, representado pelas variáveis integridade e status. Qualquer falha nesses parâmetros implica na inviabilidade imediata da decolagem, sendo considerados fatores eliminatórios.

## 5.6 Reflexão crítica

A exploração espacial representa um dos maiores avanços tecnológicos da humanidade, porém, também levanta importantes questões relacionadas à ética, responsabilidade e sustentabilidade. O desenvolvimento de sistemas autônomos, como os utilizados na missão Aurora Siger, exige que decisões críticas sejam tomadas por algoritmos, o que reforça a necessidade de garantir transparência e responsabilidade nos processos computacionais. A utilização de dados e inteligência artificial deve ser orientada por princípios éticos, assegurando que as decisões automatizadas não coloquem em risco vidas humanas ou recursos estratégicos.

Do ponto de vista social, a exploração espacial possui impactos significativos. Por um lado, impulsiona o avanço científico, gera inovação tecnológica e contribui para o desenvolvimento de soluções que podem ser aplicadas na Terra, como melhorias em telecomunicações, monitoramento ambiental e novos materiais. Por outro lado, levanta questionamentos sobre a distribuição de recursos, uma vez que os investimentos no setor espacial são elevados e coexistem com desafios sociais urgentes, como desigualdade e acesso a tecnologias básicas. Dessa forma, é fundamental que o progresso espacial esteja alinhado a benefícios concretos para a sociedade como um todo.

A sustentabilidade tecnológica também se destaca como um fator essencial nesse contexto. Missões espaciais operam com recursos limitados, especialmente no que se refere à energia, exigindo sistemas altamente eficientes e otimizados. A preocupação com o consumo energético, redução de desperdícios e aumento da eficiência operacional é fundamental não apenas para o sucesso das missões, mas também como reflexo de práticas sustentáveis que devem ser aplicadas em escala global. Além disso, a crescente quantidade de detritos espaciais reforça a necessidade de desenvolver tecnologias mais limpas e estratégias responsáveis de utilização do espaço.

Portanto, a integração entre tecnologia, ética e sustentabilidade é indispensável para garantir que a exploração espacial ocorra de forma responsável. Mais do que alcançar novos territórios, é necessário assegurar que esse avanço contribua positivamente para a sociedade e respeite os limites ambientais e sociais, consolidando um modelo de desenvolvimento tecnológico consciente e sustentável.